name: Code Check CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
jobs:
  deploy:
    name: check code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install pytest
        run: pip install -r requirements.txt

      - name: Create .env file
        run: cp .env.example .env

      - name: Run app
        run: docker compose up -d --build

      - name: Curl
        run: |
          sleep 5s
          curl -v http://127.0.0.1:8000/health/

      - name: Unzip check folder
        run: |
          unzip tests.zip

#      - name: Download UI Test File
#        run: |
#          curl -L "${{ secrets.CHECK_FILE }}" > ui-test.py

      - name: Test database connection
        run: |
          sudo apt-get install -y postgresql-client redis-tools
          PGPASSWORD=postgres-pass psql -h localhost -p 5432 -U postgres -d blog_db -c "CREATE TABLE student(id SERIAL PRIMARY KEY, firstName VARCHAR(40) NOT NULL, lastName VARCHAR(40) NOT NULL, age INT, address VARCHAR(80), email VARCHAR(40))"
          PGPASSWORD=postgres-pass psql -h localhost -p 5432 -U postgres -d blog_db -c "INSERT INTO student(firstname, lastname, age, address, email) VALUES('test', 'test2', 12, 'test3', 'admin@admin.com') RETURNING *"
          PGPASSWORD=postgres-pass psql -h localhost -p 5432 -U postgres -d blog_db -c "SELECT * FROM student"
        continue-on-error: true

      - name: Run UI Tests
        run: docker compose exec app pytest -vv --json-report --json-report-file=./reports/ui-checker-report.json --json-report-indent=2
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-checker-artifact
          path: ./newman/api-checker-report.json

      - name: Send run_id
        run: |
          curl --location 'https://api-dev.mohirpool.uz/api/site/accelerators/github-feedbacks/${{ github.actor }}/' \
          --header 'X-API-KEY: ${{ secrets.X_API_KEY }}' \
          --form 'action_run_id=${{ github.run_id }}' \
          --form 'project=${{ secrets.PROJECT_ID }}'