name: Unittest Check CI/CD with error
on:
  workflow_dispatch:
  push:
    branches: [ "unittest-with-error" ]
jobs:
  deploy:
    name: check code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Create .env file
        run: cp .env.example .env

      - name: Run app
        run: docker compose up -d --build

      - name: Curl
        run: |
          sleep 5s
          curl -v http://127.0.0.1:8000/health/

      - name: Download test zip File
        run: |
          curl -L "${{ secrets.CHECK_FILE }}" > tests.zip

      - name: Unzip check test zip folder
        run: |
          unzip tests.zip

      - name: Run Tests
        run: docker compose exec app pytest -vv --json-report --json-report-file=./reports/unittest-checker-report.json --json-report-indent=2
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unittest-checker-artifact
          path: ./reports/unittest-checker-report.json

      - name: Send run_id
        run: |
          curl --location 'https://api-dev.mohirpool.uz/api/site/accelerators/code-reviews/github-feedbacks/${{ github.actor }}/' \
          --header 'X-API-KEY: ${{ secrets.X_API_KEY }}' \
          --form 'action_run_id=${{ github.run_id }}' \
          --form 'project=${{ secrets.PROJECT_ID }}'